name: Deploy

on:
  push:
    branches:
      - example/env-vars

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nestjs-docker-heroku-example"
          heroku_email: "shariqhirani2010@gmail.com"
          usedocker: true
          docker_build_args: |
            TEST_ARG
        env:
          TEST_ARG: ${{secrets.TEST_ENV}}
